version: "3.9"
services:
  web:
    depends_on:
      - postgres_db
    build:
      context: ./web
      dockerfile: Dockerfile
    image: testtask-local:v1
    env_file:
      - web/.env
    ports:
      - "8000:8000"
    volumes:
      - ./web/:/app/
    command: sh -c "chmod +x /app/migrate.sh &&
                    sh /app/migrate.sh &&
                    /opt/venv/bin/python manage.py runserver 0.0.0.0:8000"
  postgres_db:
    image: postgres
    command: -p 5434
    env_file:
      - web/.env
    expose:
      - 5434
    ports:
      - "5434:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: