# Generated by Django 5.0 on 2024-06-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_closing_date_alter_task_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("P", "pending"), ("IP", "in process"), ("D", "done")],
                default="P",
                max_length=2,
            ),
        ),
    ]
