# Generated by Django 5.0 on 2024-06-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="closing_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
